server:
  port: 8081
spring:
  application:
    name: accounts
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/accounts
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: amqp://localhost:5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
