server:
  port: 8082
spring:
  application:
    name: notifications
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: amqp://localhost:5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
rabbitmq:
  exchanges:
    internal: internal.exchange
  queue:
    notifications: notifications.queue
  routing-keys:
    internal-notifications: internal.notifications.routing-key
